modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="runecraft"
version="1.0.0"
displayName="runecraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Lap top, MCreator"

[[dependencies.runecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



